# Generated by Django 4.2.1 on 2023-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='앨범 이미지')),
                ('title', models.CharField(max_length=128, verbose_name='앨범 제목')),
                ('content', models.TextField(default='', verbose_name='내용')),
                ('created_at', models.DateField(verbose_name='출시일')),
            ],
        ),
    ]
