# Generated by Django 4.2.1 on 2023-05-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='singer',
            field=models.TextField(default='', verbose_name='가수 이름'),
        ),
    ]
