# Generated by Django 4.2.1 on 2023-05-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='singer',
            field=models.CharField(max_length=128, verbose_name='가수 이름'),
        ),
    ]
