# Generated by Django 4.2.1 on 2023-05-18 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='출시일'),
        ),
    ]
