# Generated by Django 4.2.1 on 2023-05-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_list_writer_alter_list_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=128, verbose_name='응원글 내용'),
        ),
    ]
